添加pr门禁对前端打包测试

diff --git a/.github/workflows/build-package-check.yml b/.github/workflows/build-package-check.yml
--- a/.github/workflows/build-package-check.yml
+++ b/.github/workflows/build-package-check.yml
@@ -6,7 +6,7 @@ on:
       - master # 触发条件，比如当推送至main分支时
 
 jobs:
-  build:
+  build-backend:
     runs-on: ubuntu-latest # 使用的运行环境
 
     steps:
@@ -23,6 +23,37 @@ jobs:
         run: |
           mvn package  # 执行打包命令，跳过测试以加速
           if [ $? -ne 0 ]; then
-            echo "Packaging failed, exiting with error code 1"
+            echo "Packaging Backend failed, exiting with error code 1"
             exit 1
+          fi
+  build-frontend:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '16'
+      - name: Cache pnpm modules
+        uses: actions/cache@v2
+        with:
+          path: ~/.pnpm-store
+          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-pnpm-
+      - name: Install pnpm
+        run: npm install -g pnpm
+      - name: Change Directory to Mixi-UI
+        run: cd Mixi-ui
+      - name: Install Dependencies
+        working-directory: Mixi-ui
+        run: pnpm install
+      - name: Build Frontend
+        working-directory: Mixi-ui
+        run: |
+          pnpm build
+          if [ $? -ne 0 ]; then
+              echo "Packaging Frontend failed, exiting with error code 1"
+              exit 1
           fi
